# This workflow publishes a pre-release version of the extension to the VSCode marketplace.
name: Publish pre-release to the Visual Studio Code Marketplace
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Install dependencies
      run: npm install

    - name: Get package.json version
      id: get-version
      uses: beaconbrigade/package-json-version@v1

    - name: Tag nightly version
      run: npm version "${{ steps.get-version.outputs.version }}-$(date %Y%m%d)"

    - name: Publish
      run: |
        npm run package -- --pre-release
        npm run publish -- --pre-release -p "${{ secrets.VSCODE_MARKETPLACE_TOKEN }}"
