# This workflow publishes the extension to the VSCode marketplace
name: Publish to Visual Studio Code Marketplace
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Get the package version
      id: get_version
      run: echo "PACKAGE_VERSION=$(jq -r '.version' package.json)" >> "$GITHUB_OUTPUT"

    - name: Detect invalid version
      id: version_check
      if: ${{ mod( steps.get_version.outputs.PACKAGE_VERSION, 2 ) != 0 }}
      run: exit 1

    - name: Install dependencies
      id: install_deps
      run: npm install

    - name: Package
      id: package
      run: npm run package

    - name: Publish
      id: publish
      run: npm run publish -- -p "${{ secrets.VSCODE_MARKETPLACE_TOKEN }}"
