# This workflow publishes the extension to the VSCode marketplace
name: Publish to Visual Studio Code Marketplace
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Get the package version
      id: get_version
      run: |
        PACKAGE_VERSION=$(jq -r '.version' package.json)
        MINOR_VERSION=$(echo "$PACKAGE_VERSION" | cut -d'.' -f2)
        echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> "$GITHUB_OUTPUT"
        echo "MINOR_VERSION=$MINOR_VERSION" >> "$GITHUB_OUTPUT"

    - name: Detect invalid version
      id: version_check
      run: |
        MINOR_VERSION=${{ steps.get_version.outputs.MINOR_VERSION }}
        if (( MINOR_VERSION % 2 != 0 )); then
          exit 1
        fi

    - name: Install dependencies
      id: install_deps
      run: npm install

    - name: Package
      id: package
      run: npm run package

    - name: Publish
      id: publish
      run: npm run publish -- -p "${{ secrets.VSCODE_MARKETPLACE_TOKEN }}"
